services:
  data_generation:
    build: .
    container_name: data-generation-service
    command: src/data_generator.py

  schedule_generation:
    build: .
    container_name: schedule-generation-service
    command: src/schedule_update.py
